name: Terraform Validate

on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Terraform Init for IAM Users
        working-directory: ./modules/iam/users
        run: terraform init

      - name: Terraform Validate for IAM Users
        working-directory: ./modules/iam/users
        run: terraform validate

      - name: Terraform Init for IAM Roles
        working-directory: ./modules/iam/roles
        run: terraform init

      - name: Terraform Validate for IAM Roles
        working-directory: ./modules/iam/roles
        run: terraform validate

      - name: Terraform Init for Network
        working-directory: ./modules/network
        run: terraform init

      - name: Terraform Validate for Network
        working-directory: ./modules/network
        run: terraform validate

      - name: Terraform Init for Cognito
        working-directory: ./modules/auth
        run: terraform init

      - name: Terraform Validate for Cognito
        working-directory: ./modules/auth
        run: terraform validate